import type { Metadata } from "next";
import { zenMaruGothicFont } from "../../utils/fonts";
import "./globals.css";
import ConditionalLayout from "@/components/ConditionalLayout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zenMaruGothicFont.variable} flex flex-col h-screen bg-background font-body text-text lg:text-lg sm:text-xl font-medium text-justify w-full overflow-x-hidden`}
      >
        <ConditionalLayout>{children}</ConditionalLayout>
      </body>
    </html>
  );
}
